program Authenticator;

uses
  System.StartUpCopy,
  FMX.Forms,
  Skia.FMX,
  FMX.Types,
  TOTP.Main in 'TOTP.Main.pas' {FormMain},
  OTP.Consts in 'DelphiOTP\src\consts\OTP.Consts.pas',
  OTP.Contract.Core.Calculator in 'DelphiOTP\src\contracts\OTP.Contract.Core.Calculator.pas',
  OTP.Contract.Core.SecretGenerator in 'DelphiOTP\src\contracts\OTP.Contract.Core.SecretGenerator.pas',
  OTP.Contract.Core.Validator in 'DelphiOTP\src\contracts\OTP.Contract.Core.Validator.pas',
  OTP.Core.Calculator in 'DelphiOTP\src\cores\OTP.Core.Calculator.pas',
  OTP.Core.SecretGenerator in 'DelphiOTP\src\cores\OTP.Core.SecretGenerator.pas',
  OTP.Core.Validator in 'DelphiOTP\src\cores\OTP.Core.Validator.pas',
  OPT.Exception.InvalidToken in 'DelphiOTP\src\exceptions\OPT.Exception.InvalidToken.pas',
  OTP.Helper.ArrayBytes in 'DelphiOTP\src\helpers\OTP.Helper.ArrayBytes.pas',
  OTP.Resource.Exception in 'DelphiOTP\src\resources\OTP.Resource.Exception.pas',
  OTP in 'DelphiOTP\src\OTP.pas',
  OTP.Helper.Base32 in 'DelphiOTP\src\helpers\OTP.Helper.Base32.pas',
  TOTP.Generator in 'TOTP.Generator.pas',
  OTP.Types in 'DelphiOTP\src\types\OTP.Types.pas',
  OTP.Core.URL in 'DelphiOTP\src\cores\OTP.Core.URL.pas',
  TOTP.Frame.Key in 'TOTP.Frame.Key.pas' {FrameKey: TFrame},
  TOTP.QRScan in 'TOTP.QRScan.pas',
  ZXing.OneD.Code128Reader in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.Code128Reader.pas',
  ZXing.OneD.Code39Reader in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.Code39Reader.pas',
  ZXing.OneD.Code93Reader in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.Code93Reader.pas',
  ZXing.OneD.EAN13Reader in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.EAN13Reader.pas',
  ZXing.OneD.EAN8Reader in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.EAN8Reader.pas',
  ZXing.OneD.EANManufacturerOrgSupport in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.EANManufacturerOrgSupport.pas',
  ZXing.OneD.ITFReader in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.ITFReader.pas',
  ZXing.OneD.OneDReader in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.OneDReader.pas',
  ZXing.OneD.UPCAReader in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.UPCAReader.pas',
  ZXing.OneD.UPCEANExtension2Support in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtension2Support.pas',
  ZXing.OneD.UPCEANExtension5Support in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtension5Support.pas',
  ZXing.OneD.UPCEANExtensionSupport in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANExtensionSupport.pas',
  ZXing.OneD.UPCEANReader in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEANReader.pas',
  ZXing.OneD.UPCEReader in '..\#Fork\ZXing.Delphi\Lib\Classes\1D Barcodes\ZXing.OneD.UPCEReader.pas',
  ZXing.Datamatrix.Internal.BitMatrixParser in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.BitMatrixParser.pas',
  ZXing.Datamatrix.Internal.DataBlock in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.DataBlock.pas',
  ZXing.Datamatrix.Internal.DecodedBitStreamParser in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.DecodedBitStreamParser.pas',
  ZXing.Datamatrix.Internal.Decoder in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.Decoder.pas',
  ZXing.Datamatrix.Internal.Version in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.Version.pas',
  ZXing.QrCode.Internal.BitMatrixParser in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.BitMatrixParser.pas',
  ZXing.QrCode.Internal.DataBlock in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DataBlock.pas',
  ZXing.QrCode.Internal.DataMask in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DataMask.pas',
  ZXing.QrCode.Internal.DecodedBitStreamParser in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DecodedBitStreamParser.pas',
  ZXing.QrCode.Internal.Decoder in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Decoder.pas',
  ZXing.QrCode.Internal.ErrorCorrectionLevel in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.ErrorCorrectionLevel.pas',
  ZXing.QrCode.Internal.FormatInformation in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.FormatInformation.pas',
  ZXing.QrCode.Internal.Mode in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Mode.pas',
  ZXing.QrCode.Internal.QRCodeDecoderMetaData in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.QRCodeDecoderMetaData.pas',
  ZXing.QrCode.Internal.Version in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Version.pas',
  ZXing.Datamatrix.Internal.Detector in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Detector\ZXing.Datamatrix.Internal.Detector.pas',
  ZXing.QrCode.Internal.AlignmentPattern in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPattern.pas',
  ZXing.QrCode.Internal.AlignmentPatternFinder in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPatternFinder.pas',
  ZXing.QrCode.Internal.AlignmentPatternImplementation in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPatternImplementation.pas',
  ZXing.QrCode.Internal.Detector in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.Detector.pas',
  ZXing.QrCode.Internal.FinderPattern in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPattern.pas',
  ZXing.QrCode.Internal.FinderPatternFinder in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternFinder.pas',
  ZXing.QrCode.Internal.FinderPatternImplementation in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternImplementation.pas',
  ZXing.QrCode.Internal.FinderPatternInfo in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternInfo.pas',
  ZXing.Datamatrix.DataMatrixReader in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\ZXing.Datamatrix.DataMatrixReader.pas',
  ZXing.QrCode.QRCodeReader in '..\#Fork\ZXing.Delphi\Lib\Classes\2D Barcodes\ZXing.QrCode.QRCodeReader.pas',
  ZXing.Common.Detector.MathUtils in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\Detector\ZXing.Common.Detector.MathUtils.pas',
  ZXing.Common.Detector.WhiteRectangleDetector in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\Detector\ZXing.Common.Detector.WhiteRectangleDetector.pas',
  ZXing.Common.ReedSolomon.GenericGF in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ReedSolomon\ZXing.Common.ReedSolomon.GenericGF.pas',
  ZXing.Common.ReedSolomon.ReedSolomonDecoder in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ReedSolomon\ZXing.Common.ReedSolomon.ReedSolomonDecoder.pas',
  ZXing.BarcodeFormat in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.BarcodeFormat.pas',
  ZXing.BitSource in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.BitSource.pas',
  ZXIng.ByteSegments in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXIng.ByteSegments.pas',
  ZXing.CharacterSetECI in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.CharacterSetECI.pas',
  ZXing.Common.BitArray in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.Common.BitArray.pas',
  ZXing.Common.BitArrayImplementation in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.Common.BitArrayImplementation.pas',
  ZXing.Common.BitMatrix in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.Common.BitMatrix.pas',
  ZXing.Common.DetectorResult in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.Common.DetectorResult.pas',
  ZXing.Common.GridSampler in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.Common.GridSampler.pas',
  ZXing.Common.PerspectiveTransform in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.Common.PerspectiveTransform.pas',
  ZXing.DecodeHintType in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.DecodeHintType.pas',
  ZXing.DecoderResult in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.DecoderResult.pas',
  ZXing.DefaultGridSampler in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.DefaultGridSampler.pas',
  ZXing.EncodeHintType in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.EncodeHintType.pas',
  ZXing.Helpers in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.Helpers.pas',
  ZXing.MultiFormatReader in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.MultiFormatReader.pas',
  ZXing.Reader in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.Reader.pas',
  ZXing.ReadResult in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.ReadResult.pas',
  ZXing.ResultMetadataType in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.ResultMetadataType.pas',
  ZXing.ResultPoint in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.ResultPoint.pas',
  ZXing.ResultPointImplementation in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.ResultPointImplementation.pas',
  ZXing.StringUtils in '..\#Fork\ZXing.Delphi\Lib\Classes\Common\ZXing.StringUtils.pas',
  ZXing.BaseLuminanceSource in '..\#Fork\ZXing.Delphi\Lib\Classes\Filtering\ZXing.BaseLuminanceSource.pas',
  ZXing.Binarizer in '..\#Fork\ZXing.Delphi\Lib\Classes\Filtering\ZXing.Binarizer.pas',
  ZXing.BinaryBitmap in '..\#Fork\ZXing.Delphi\Lib\Classes\Filtering\ZXing.BinaryBitmap.pas',
  ZXing.GlobalHistogramBinarizer in '..\#Fork\ZXing.Delphi\Lib\Classes\Filtering\ZXing.GlobalHistogramBinarizer.pas',
  ZXing.HybridBinarizer in '..\#Fork\ZXing.Delphi\Lib\Classes\Filtering\ZXing.HybridBinarizer.pas',
  ZXing.InvertedLuminanceSource in '..\#Fork\ZXing.Delphi\Lib\Classes\Filtering\ZXing.InvertedLuminanceSource.pas',
  ZXing.LuminanceSource in '..\#Fork\ZXing.Delphi\Lib\Classes\Filtering\ZXing.LuminanceSource.pas',
  ZXing.RGBLuminanceSource in '..\#Fork\ZXing.Delphi\Lib\Classes\Filtering\ZXing.RGBLuminanceSource.pas',
  ZXing.ScanManager in '..\#Fork\ZXing.Delphi\Lib\Classes\ZXing.ScanManager.pas';

{$R *.res}

begin
  GlobalUseSkia := True;
  Application.Initialize;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
